spring.application.name=forohub

spring.datasource.url=jdbc:mysql://${DB_HOST}/${DB_NAME_FOROHUB}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER_MYSQL}
spring.datasource.password=${DB_PASSWORD_MYSQL}

api.security.token.secret=${JWT_SECRET_APIVOLLMED:123456}